import { DriveFile } from '../types';

export const listDriveFiles = async (
  accessToken: string,
  searchQuery?: string,
  filterType?: string
): Promise<DriveFile[]> => {
  // If demo workspace token is provided, simulate Google Drive files
  if (accessToken.startsWith('demo-')) {
    let files: DriveFile[] = SAMPLE_DOCUMENTS.map((doc) => ({
      id: doc.id,
      name: doc.name,
      mimeType: doc.type === 'iso20022' ? 'text/xml' : doc.type === 'cloud_bill' ? 'application/vnd.google-apps.spreadsheet' : 'application/vnd.google-apps.document',
      size: `${Math.round(doc.fullContent.length / 100) / 10} KB`,
      modifiedTime: new Date(Date.now() - 3600 * 1000 * (SAMPLE_DOCUMENTS.indexOf(doc) + 1) * 4).toISOString(),
      iconLink: 'https://ssl.gstatic.com/docs/doclist/images/icon_10_generic_list.png',
      webViewLink: '#',
    }));

    if (searchQuery && searchQuery.trim()) {
      const q = searchQuery.toLowerCase().trim();
      files = files.filter((f) => f.name.toLowerCase().includes(q));
    }

    if (filterType === 'documents') {
      files = files.filter((f) => !f.mimeType.includes('spreadsheet'));
    } else if (filterType === 'spreadsheets') {
      files = files.filter((f) => f.mimeType.includes('spreadsheet'));
    }

    return files;
  }

  let query = 'trashed = false';
  if (searchQuery && searchQuery.trim()) {
    query += ` and name contains '${searchQuery.trim().replace(/'/g, "\\'")}'`;
  }
  if (filterType === 'documents') {
    query += " and (mimeType contains 'document' or mimeType contains 'pdf' or mimeType contains 'text')";
  } else if (filterType === 'spreadsheets') {
    query += " and (mimeType contains 'spreadsheet' or mimeType contains 'csv' or mimeType contains 'sheet')";
  }

  const url = new URL('https://www.googleapis.com/drive/v3/files');
  url.searchParams.set('pageSize', '30');
  url.searchParams.set(
    'fields',
    'files(id,name,mimeType,size,modifiedTime,iconLink,webViewLink,thumbnailLink)'
  );
  url.searchParams.set('orderBy', 'modifiedTime desc');
  url.searchParams.set('q', query);

  const response = await fetch(url.toString(), {
    headers: {
      Authorization: `Bearer ${accessToken}`,
      Accept: 'application/json',
    },
  });

  if (!response.ok) {
    const err = await response.json().catch(() => ({}));
    throw new Error(err.error?.message || `Failed to fetch Drive files: ${response.statusText}`);
  }

  const data = await response.json();
  return (data.files || []).map((f: any) => ({
    id: f.id,
    name: f.name,
    mimeType: f.mimeType,
    size: f.size,
    modifiedTime: f.modifiedTime,
    iconLink: f.iconLink,
    webViewLink: f.webViewLink,
    thumbnailLink: f.thumbnailLink,
  }));
};

export const fetchFileContent = async (
  accessToken: string,
  fileId: string,
  mimeType: string
): Promise<string> => {
  if (accessToken.startsWith('demo-')) {
    const sample = SAMPLE_DOCUMENTS.find((s) => s.id === fileId);
    if (sample) return sample.fullContent;
    return `[Demo File Content for ${fileId}]\nStatus: Successfully loaded from Demo Drive Workspace.`;
  }

  let url = `https://www.googleapis.com/drive/v3/files/${fileId}?alt=media`;

  // For Google Workspace Docs, export as plain text
  if (mimeType.includes('google-apps.document')) {
    url = `https://www.googleapis.com/drive/v3/files/${fileId}/export?mimeType=text/plain`;
  } else if (mimeType.includes('google-apps.spreadsheet')) {
    url = `https://www.googleapis.com/drive/v3/files/${fileId}/export?mimeType=text/csv`;
  }

  const response = await fetch(url, {
    headers: {
      Authorization: `Bearer ${accessToken}`,
    },
  });

  if (!response.ok) {
    throw new Error(`Failed to read file contents: ${response.statusText}`);
  }

  const text = await response.text();
  return text;
};

export const saveReportToDrive = async (
  accessToken: string,
  filename: string,
  content: string,
  mimeType: string = 'text/markdown'
): Promise<{ id: string; name: string; webViewLink?: string }> => {
  if (accessToken.startsWith('demo-')) {
    return {
      id: `demo-file-${Date.now()}`,
      name: filename,
      webViewLink: 'https://drive.google.com/drive/my-drive',
    };
  }

  const boundary = '-------314159265358979323846';

  const delimiter = `\r\n--${boundary}\r\n`;
  const closeDelimiter = `\r\n--${boundary}--`;

  const metadata = {
    name: filename,
    mimeType: mimeType,
    description: 'Generated by B2B SaaS Document Intelligence Platform',
  };

  const multipartRequestBody =
    delimiter +
    'Content-Type: application/json; charset=UTF-8\r\n\r\n' +
    JSON.stringify(metadata) +
    delimiter +
    `Content-Type: ${mimeType}\r\n\r\n` +
    content +
    closeDelimiter;

  const response = await fetch(
    'https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,webViewLink',
    {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${accessToken}`,
        'Content-Type': `multipart/related; boundary=${boundary}`,
      },
      body: multipartRequestBody,
    }
  );

  if (!response.ok) {
    const err = await response.json().catch(() => ({}));
    throw new Error(err.error?.message || `Failed to save file to Drive: ${response.statusText}`);
  }

  return await response.json();
};

// Preset sample enterprise documents matching the user's top categories
export interface SampleDoc {
  id: string;
  name: string;
  type: 'invoice' | 'contract' | 'cloud_bill' | 'iso20022' | 'construction_spec';
  categoryTitleBn: string;
  categoryTitleEn: string;
  previewSnippet: string;
  fullContent: string;
}

export const SAMPLE_DOCUMENTS: SampleDoc[] = [
  {
    id: 'sample-inv-001',
    name: 'Enterprise_Tech_Invoice_INV-8492.txt',
    type: 'invoice',
    categoryTitleBn: 'আর্থিক চালান ও অডিট (AI Document Intelligence)',
    categoryTitleEn: 'Vendor Invoice & Financial Audit',
    previewSnippet: 'Invoice #INV-8492 | Vendor: Apex Cloud Systems LLC | Net 30 | Total: $14,850.00',
    fullContent: `=====================================================
INVOICE: #INV-8492
ISSUED BY: Apex Cloud Systems LLC, 500 Tech Parkway, Austin, TX
BILL TO: Global Logistics Corp, Wilmington, DE
INVOICE DATE: 2026-08-15
DUE DATE: 2026-09-14 (Net 30)
PAYMENT TERMS: Bank Wire / SWIFT
-----------------------------------------------------
LINE ITEMS:
1. Enterprise Cloud Proxy Engine (Q3 License)
   Quantity: 1 | Unit Price: $8,500.00 | Total: $8,500.00
2. Managed ISO 20022 Data Conversion Pipeline
   Quantity: 120,000 tx | Rate: $0.035/tx | Total: $4,200.00
3. Dedicated SLA 24/7 Security Escalation Support
   Quantity: 1 | Unit Price: $1,500.00 | Total: $1,500.00
4. Unallocated Compute Surcharge (Unverified)
   Quantity: 1 | Unit Price: $650.00   | Total: $650.00

SUBTOTAL: $14,850.00
APPLICABLE TAX (0% - B2B Exempt with ID #TX-994102): $0.00
DISCOUNT APPLIED (Early Payment 5% if paid in 10 days): -$742.50
TOTAL BALANCE DUE: $14,107.50
-----------------------------------------------------
BANK DETAILS FOR PAYMENT:
Bank Name: First Sovereign Bank NY
SWIFT: FSBNUS33XXX
Account No: 9820-4100-2918
IBAN: US82FSBN982041002918
-----------------------------------------------------
AUDIT NOTE: Ensure line item #4 is matched against active contract SLA.`,
  },
  {
    id: 'sample-contract-002',
    name: 'SaaS_Vendor_Master_Service_Agreement.txt',
    type: 'contract',
    categoryTitleBn: 'আইনি চুক্তি ও কমপ্লায়েন্স অডিট (Legal Contract Intelligence)',
    categoryTitleEn: 'Master Service Agreement & SLA Contract',
    previewSnippet: 'Parties: DataMesh AI Inc. & Metro Health Networks | Uptime 99.9% | HIPAA Compliant',
    fullContent: `=====================================================
MASTER SERVICES AGREEMENT & DATA PROCESSING ADDENDUM
EFFECTIVE DATE: October 1, 2026
PARTIES:
Party A: DataMesh AI Technologies Inc. ("Provider")
Party B: Metro Regional Health Network Inc. ("Client")

1. SERVICES & SCOPE:
Provider grants Client non-exclusive, multi-seat access to its Practice Management & AI Document Extraction Engine.
Monthly Subscription Tier: Enterprise Tier ($1,850.00 / month, billed annually).

2. SERVICE LEVEL AGREEMENT (SLA):
2.1 Uptime Commitment: 99.95% monthly availability excluding scheduled maintenance windows.
2.2 SLA Penalty: If uptime falls below 99.5%, Client is entitled to a 20% billing credit for the subsequent monthly billing cycle.

3. DATA PRIVACY, SECURITY & HIPAA:
3.1 Business Associate Agreement (BAA): The software handles Protected Health Information (PHI). Provider warrants full compliance with HIPAA, HITECH, and SOC-2 Type II standards.
3.2 Data Residency: All PHI data must reside within encrypted-at-rest AWS US-East vaults (AES-256).

4. TERMINATION & AUTO-RENEWAL:
4.1 Term: Initial term of twelve (12) months.
4.2 Auto-Renewal: Agreement automatically renews for consecutive 12-month periods UNLESS either party provides written notice at least sixty (60) days prior to the expiration date.
4.3 Early Termination for Convenience Penalty: 50% of remaining contract value.

5. LIABILITY & INDEMNIFICATION:
Aggregate liability capped at fees paid in the preceding 12 months, except in cases of gross negligence or willful data breaches where liability is uncapped.`,
  },
  {
    id: 'sample-cloud-003',
    name: 'AWS_GoogleCloud_Waste_Report_Aug2026.txt',
    type: 'cloud_bill',
    categoryTitleBn: 'ক্লাউড খরচ গভর্নেন্স ও অপটিমাইজেশন (Cloud Cost Tracker)',
    categoryTitleEn: 'Multi-Cloud Infrastructure Cost & Idle Waste Audit',
    previewSnippet: 'Total Monthly Spend: $38,420 | Idle EC2: $6,840/mo | Orphaned EBS Volumes: $1,420/mo',
    fullContent: `=====================================================
CLOUD INFRASTRUCTURE SPEND & WASTE AUDIT REPORT
Account: Production & Staging Workloads (AWS & GCP)
Billing Period: 2026-08-01 to 2026-08-31
Total Gross Cloud Spend: $38,420.00
Estimated Wastage / Unoptimized Spend: $11,280.00 (29.3%)

DETAILED FINDINGS & IDLE WORKLOADS:
1. Unattached EBS Volumes & Idle Disk Snapshots
   - 48 gp3 volumes unattached > 30 days
   - Monthly Waste: $1,420.00
   - Recommendation: Auto-archive snapshots to S3 Glacier, delete idle volumes.

2. Overprovisioned EC2 Instances (Staging & Dev)
   - 14 x c5.4xlarge instances averaging < 4.2% CPU utilization over 60 days
   - Monthly Cost: $9,640.00
   - Optimized Cost with Spot / Graviton t4g: $2,800.00
   - Monthly Waste: $6,840.00

3. Cross-AZ Data Transfer Spikes:
   - Kafka cluster cross-availability zone uncompressed traffic: $2,120.00
   - Fix: Configure VPC endpoints and internal peering.
   - Monthly Savings Potential: $1,650.00

4. Unused Cloud SQL & RDS Multi-AZ Replicas in Staging:
   - 2 multi-AZ test databases left running 24/7 over weekends
   - Monthly Waste: $1,370.00

TOTAL IMMEDIATE MONTHLY REVENUE SAVINGS FOR CLIENT: $11,280.00
SAAS PRICING CAPTURE (15% OF SAVINGS MODEL): $1,692.00 / month recurring.`,
  },
  {
    id: 'sample-iso-004',
    name: 'SWIFT_ISO20022_pacs008_Payment_Payload.xml',
    type: 'iso20022',
    categoryTitleBn: 'ফিনটেক ও ISO 20022 মেসেজিং মিডলওয়্যার (FinTech Middleware)',
    categoryTitleEn: 'ISO 20022 XML Message (pacs.008.001.08)',
    previewSnippet: 'Format: pacs.008.001.08 | Amount: $2,450,000.00 USD | Cross-Border Compliance Validated',
    fullContent: `<?xml version="1.0" encoding="UTF-8"?>
<Document xmlns="urn:iso:std:iso:20022:tech:xsd:pacs.008.001.08">
  <FIToFICstmrCdtTrf>
    <GrpHdr>
      <MsgId>MSG-20260824-8849102</MsgId>
      <CreDtTm>2026-08-24T14:32:00Z</CreDtTm>
      <NbOfTxs>1</NbOfTxs>
      <SttlmInf>
        <SttlmMtd>CLRG</SttlmMtd>
        <ClrSys>
          <Prtry>FEDNOW_ISO</Prtry>
        </ClrSys>
      </SttlmInf>
    </GrpHdr>
    <CdtTrfTxInf>
      <PmtId>
        <EndToEndId>E2E-CORP-SETTLE-7729</EndToEndId>
        <UETR>c9b1f200-50de-44cf-a82f-891d4e0828ac</UETR>
      </PmtId>
      <IntrBkSttlmAmt Ccy="USD">2450000.00</IntrBkSttlmAmt>
      <IntrBkSttlmDt>2026-08-25</IntrBkSttlmDt>
      <Dbtr>
        <Nm>Nexus Maritime Logistics Inc</Nm>
        <PstlAdr><Ctry>SG</Ctry></PstlAdr>
      </Dbtr>
      <DbtrAgt>
        <FinInstnId><BICFI>DBSGSGSGXXX</BICFI></FinInstnId>
      </DbtrAgt>
      <CdtrAgt>
        <FinInstnId><BICFI>CHASUS33XXX</BICFI></FinInstnId>
      </CdtrAgt>
      <Cdtr>
        <Nm>Atlantic Port Operators LLC</Nm>
        <PstlAdr><Ctry>US</Ctry></PstlAdr>
      </Cdtr>
      <RmtInf>
        <Ustrd>Q3 Port Fuel & Berthing Tariff Settlement Invoice #BF-9921</Ustrd>
      </RmtInf>
    </CdtTrfTxInf>
  </FIToFICstmrCdtTrf>
</Document>`,
  },
  {
    id: 'sample-const-005',
    name: 'Construction_Takeoff_Commercial_Tower.txt',
    type: 'construction_spec',
    categoryTitleBn: 'কনস্ট্রাকশন বিড ও টেকঅফ (Vertical SaaS & Takeoff Spec)',
    categoryTitleEn: 'Commercial Tower Architectural Takeoff & Cost Estimation',
    previewSnippet: 'Project: Metro Horizon Tower | Structural Concrete: 8,400 cu.yd | Total Bid: $4.2M',
    fullContent: `=====================================================
CONSTRUCTION TAKEOFF & MATERIAL SPECIFICATION
PROJECT: Metro Horizon Commercial Center (12 Stories)
LOCATION: Chicago, IL
ARCHITECTURAL DWG REF: ARCH-S204-REV3
ESTIMATOR: BuildMetric AI Automated Takeoff Engine
-----------------------------------------------------
QUANTITY TAKEOFF (QTO) SUMMARY:
1. Structural Concrete (4,000 PSI Ready Mix):
   - Foundation & Footings: 2,800 cu. yd @ $165.00/yd = $462,000.00
   - Suspended Slabs (Post-Tensioned): 5,600 cu. yd @ $190.00/yd = $1,064,000.00

2. Reinforcing Steel (Grade 60 Deformed Rebar):
   - 420 Tons @ $1,380.00/Ton = $579,600.00
   - Labor Placement (6,720 man-hours @ $68.00/hr) = $456,960.00

3. Exterior Glazing & Curtain Wall System:
   - High-efficiency Low-E Double Glazed: 48,000 sq.ft @ $62.00/sq.ft = $2,976,000.00

4. Mechanical, Electrical & Plumbing (MEP Rough-in allowance):
   - Lump sum baseline estimate: $1,250,000.00

DIRECT MATERIAL & LABOR BASELINE: $6,788,560.00
CONTRACTOR OVERHEAD & PROFIT (12.5%): $848,570.00
CONTINGENCY RISK BUFFER (5%): $381,856.00
FINAL ESTIMATED COMPETITIVE BID SUBMISSION: $8,018,986.00
ESTIMATION TIME: 3.2 minutes (Manual equivalent: 42 engineering hours)`,
  },
];
